Pelican-Elegant/elegant

templates/_includes/disqus_scripts.html
templates/_includes/stat_counter.html
templates/base.html
templates/search.html

Remove forcing of protocol to avoid mixed mode SSL

---

templates/archives.html
templates/article.html
templates/base.html
templates/categories.html
templates/index.html
templates/tags.html

Remove hardcoded paths  for archives, tags and categories

---

.travis.yml
tests/pelicanconf.py
tests/peru.yaml
tests/test-requirements.txt

This PR does run pelican against the latest 'documentation' content to validate the commit being valid to render the pages
Related with #191

Validate commits

---

templates/archives.html

Fix #202. Change code to conform to Jinaj 2.10 API

---

templates/archives.html
templates/article.html
templates/base.html
templates/categories.html
templates/index.html
templates/tags.html

Utilizes the jinja `default` function instead of the `or` operator.
More information about how to use this function can be found in the jinja documentation: http://jinja.pocoo.org/docs/2.10/templates/#default
Closes #213

Uses jinja default() instead of or operator

---

README.md

Replace some links

---

.travis.yml
tests/pelicanconf.py
tests/peru.yaml
tests/test-requirements.txt
tests/trigger-build.js

Return travis yaml to branch

---

setup.cfg
setup.py

Add setup.py using pbr so that it creates Changelog and Authors

---

.travis.yml
tests/test-requirements.txt

Test w3c validation on generated output

---

templates/article.html

Use 'redirect' instead of 'jump'

---

CONTRIBUTING.md

Add voting mechanism and some Git newbie help

---

templates/base.html

Include CLAIM's for Google and Bing if defined

---

.hound.yml
.hound/ignoredfiles

Attempt to have hound ignoring tipue files

---

static/css/elegant.css
static/tipuesearch/tipuesearch.css

and make sure result page uses Elegant typography

Fix #260. Fix style changes introduced by tipue

---

CHANGELOG.md
templates/_includes/_defaults.html
templates/_includes/post_stats.html
templates/base.html

Only show reading time if more than 4 minutes

---

templates/_includes/share_links.html

Remove Google+ share link

---

content/Elegant - Pelican Theme/Elegant-Quickstart.md

-----
[View rendered content/Elegant - Pelican Theme/Elegant-Quickstart.md](https://github.com/Pelican-Elegant/elegant/blob/next/content/Elegant - Pelican Theme/Elegant-Quickstart.md)

Docs: Document on how to use blog-o-matic to get an Elegant blog

---

CHANGELOG.md
templates/base.html

Upgrade to FontAwesome 4.7.0

---

CHANGELOG.md
templates/_includes/analytics.html
templates/_includes/footer.html

Fix operation moving code to footer

Code for div should be in footer not in <head>

---

.hound/ignoredfiles
CHANGELOG.md
documentation/content/Supported Plugins/photogallery.md
static/magnific/magnific-popup.css
static/magnific/magnific-popup.js
templates/_includes/_defaults.html
templates/_includes/photos_footer.html
templates/_includes/photos_header.html
templates/article.html

Closes #350 
-----
[View rendered CHANGELOG.md](https://github.com/iranzo/elegant/blob/lightbox/CHANGELOG.md)

Add lightbox support for photos plugin

---

.github/pull_request_template.md

Closes #353 
-----
[View rendered .github/pull_request_template.md](https://github.com/iranzo/elegant/blob/issue353/.github/pull_request_template.md)

Define default Pull request info

---

CHANGELOG.md
documentation/content/Elegant - Pelican Theme/claimsite.md

Document website claims

---

CHANGELOG.md
templates/_includes/claim_bing.html
templates/_includes/claim_google.html
templates/base.html

Prerequisites
-------------
Recommended Steps
-----------------
Description
-----------
Closes #365 
-----
[View rendered CHANGELOG.md](https://github.com/iranzo/elegant/blob/claimsep/CHANGELOG.md)

Separate claims for Google/Bing into includes

---

documentation/content/Contributing/community-driven-project.md
documentation/content/Development/travis-ci-and-doc-website.md
documentation/content/Development/travis-to-trigger-build-in-another-repo.md
documentation/content/Elegant - Pelican Theme/Elegant-Quickstart.md
documentation/content/Elegant - Pelican Theme/article-redirect.md
documentation/pelicanconf.py

Update author blurb and articles

---

documentation/content/Search/tipue-search.md

docs(update): corrections in search article

---

documentation/pelicanconf.py

Signed-off-by: Pablo Iranzo Gómez <Pablo.Iranzo@gmail.com>

docs(update): update author avatar

---

documentation/pelicanconf.py

Setting author information in documentation to for Jack De Winter.

 docs(update): set author information

---

documentation/content/Monetization/bestazon.md
templates/_includes/footer.html

Shows banner when using bestazon
Closes #442

Show footer when using bestazon

---

static/css/admonition.css

fix(admonition): remove box shadow

---

documentation/content/Connecting With Your Readers/applause-button.md

docs(update): fix typo in applause button docs

---

documentation/content/Analytics SEO SMO/claim-site.md
templates/_includes/claim_yandex.html
templates/base.html

Add header and documentation for Claiming Website on Yandex

---

documentation/content/Components/line-numbers-code-snippet.md

Fixes part of #598 (typo in shebang)

fix typo in shebang

---

templates/_includes/last_updated.html

fix(article): use locale formatted Modified (Last Updated) date

---

.github/dependabot.yml

Sets dependabot configuration for GHA

chore: configure dependabot alerts

---

templates/base.html

fix(base.html): sets proper meta content-language for articles

---

documentation/content/Analytics SEO SMO/ms-clarity.md
templates/_includes/analytics.html

Adds support for microsoft clarity script

feat(ms-clarity): adds support for microsoft clarity

---

.github/workflows/broken-link-check.yml

Checks for broken links via GHA

(feat) Check broken links

---

.github/labels.yml
.github/workflows/label.yml

Configure the GitHub Actions issue/PR Labeler

(feat) Labeleler

---

.github/workflows/greetings.yml

Writes a messages on new issues/PR's

(feat) Greetings on new issues/pr's

---

documentation/content/Monetizing Your Blog/amazon-one-link.md
templates/_includes/footer.html

OneLink is already included in Amazon US site without any specific JavaScript code, defaulting to it and remove JavaScript dependencies in footer.html

Onelink updt

---

templates/_includes/series.html

Add striptags for series.html

---

documentation/content/101 Quick Start/updating-new-releases.md

docs(change): fix small typo
